[global]
extra-index-url=
  https://$PYPI_USERNAME:$PYPI_PASSWORD@gitlab.rossum.cloud/api/v4/projects/17/packages/pypi/simple
  https://$PYPI_USERNAME:$PYPI_PASSWORD@gitlab.rossum.cloud/api/v4/projects/646/packages/pypi/simple
  https://$PYPI_USERNAME:$PYPI_PASSWORD@gitlab.rossum.cloud/api/v4/projects/739/packages/pypi/simple
