#! /usr/bin/python
import subprocess
import sys

from isort.hooks import git_hook

if __name__ == '__main__':
    # Do not run isort if there are no commits yet, it fails
    if subprocess.run(
            ['git', 'diff-index', '--cached', '--name-only', '--diff-filter=ACMRTUXB', 'HEAD']).returncode != 128:
        sys.exit(git_hook(strict=False))
